### ISSUE TITLE
GraphDRP

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/GraphDRP#7]
SOP:

- [x] Create improve branch in model repo
- [x] Switch to improve branch in image build
- [x] Test container build
- [x] Test train with container
- [x] Test HPO
- [x] Tag improve branch with v0.6

**Comment by wilke** [comment]
SOP:
1. Image building
2. @wilke tested container: pass
3. @rajeeja tested container: todo
4. created improve branch for the release
5. Test HPO run: pass
6. Tagged improve branch v0.6
7. Change definition file to release tag
8. Test build



```
time supervisor lambda GA tests/GraphDRP/cfg-nightly.sh
...
2023-09-18 14:46:12 source_site(): sourcing /home/wilke/IMPROVE/Supervisor/workflows/common/sh/sched-lambda.sh
mkdir: created directory '/homes/wilke/IMPROVE/HPO/tmp/output/GraphDRP/EXP001/run'
mkdir: created directory '/homes/wilke/IMPROVE/HPO/tmp/output/GraphDRP/EXP001/out'
/homes/wilke/miniconda3/envs/IMPROVE/bin/python
/homes/wilke/miniconda3/envs/IMPROVE/bin/swift-t
WARN  /tmp/swift-t-workflow.Z34.swift:93:8: Variable usage warning. Variable v might be read and not written, possibly leading to deadlock
WARN  model_container.swift:15:23: variable called model_name already defined at swift-t-workflow.Z34.swift:145
WARN  model_container.swift:41:14: variable called model_name already defined at swift-t-workflow.Z34.swift:145
WARN  /home/wilke/IMPROVE/Supervisor/workflows/common/ext/EQ-Py/EQPy.swift:26: Variable usage warning. Variable loc is not used
EXIT CODE: 0

real    5m51.846s
user    16m34.684s
sys     2m8.715s
```

**Comment by wilke** [comment]
@rajeeja Please close this after verifying this model builds and we can run train with the container.

**Comment by rajeeja** [comment]
> @rajeeja Please close this after verifying this model builds and we can run train with the container.

@brettin I am not fakeroot. `FATAL:   could not use fakeroot: no mapping entry found in /etc/subuid for jain`
